# Jobs configuration.
# 
# Stores information about each job.
# 
# For example configurations, visit http://dev.bukkit.org/server-mods/jobs/.

Jobs:
  Woodcutter:
    fullname: Woodcutter
    shortname: W
    description: Дровосек. Зарабатывает деньги, сажая и срубая деревья.
    ChatColour: GREEN
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Break:
      LOG:
        income: 0.2
        experience: 0.2
    Place:
      SAPLING:
        income: 0.1
        experience: 0.1
      WOOD:
        income: 0.1
        experience: 0.1
    Kill:
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Woodcutter:
        income: 10.0
        experience: 10.0
  Miner:
    fullname: Miner
    shortname: M
    description: Шахтер. Зарабатывает деньги, добывая различные ископаемые и руды.
    ChatColour: DARK_GRAY
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Break:
      STONE:
        income: 0.25
        experience: 0.25
      COAL_ORE:
        income: 0.25
        experience: 0.25
      GLOWING_REDSTONE_ORE:
        income: 3.0
        experience: 3.0
      IRON_ORE:
        income: 4.0
        experience: 4.0
      GOLD_ORE:
        income: 5.0
        experience: 5.0
      LAPIS_ORE:
        income: 5.0
        experience: 5.0
      DIAMOND_ORE:
        income: 6.0
        experience: 6.0
      OBSIDIAN:
        income: 7.5
        experience: 7.5
      MOSSY_COBBLESTONE:
        income: 6.0
        experience: 6.0
    Place:
      RAILS:
        income: 2.0
        experience: 2.0
      IRON_ORE:
        income: -5.0
        experience: -5.0
      GOLD_ORE:
        income: -6.0
        experience: -6.0
    Kill:
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Miner:
        income: 10.0
        experience: 10.0
  Builder:
    fullname: Builder
    shortname: B
    description: Строитель. Зарабатывает деньги, делая постройки.
    ChatColour: WHITE
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Place:
      COBBLESTONE:
        income: 0.15
        experience: 0.15
      WOOD:
        income: 0.2
        experience: 0.2
      FENCE:
        income: 0.2
        experience: 0.2
      WOOL:
        income: 0.2
        experience: 0.2
      STONE:
        income: 0.15
        experience: 0.15
      GLOWSTONE:
        income: 0.3
        experience: 0.3
      SANDSTONE:
        income: 0.15
        experience: 0.15
      GLASS:
        income: 0.2
        experience: 0.2
      BRICK:
        income: 0.25
        experience: 0.25
      LAPIS_BLOCK:
        income: 0.35
        experience: 0.35
      DOUBLE_STEP:
        income: 0.15
        experience: 0.15
      STEP:
        income: 0.15
        experience: 0.15
      BOOKSHELF:
        income: 0.2
        experience: 0.2
      WOOD_STAIRS:
        income: 0.15
        experience: 0.15
      COBBLESTONE_STAIRS:
        income: 0.15
        experience: 0.15
      MOSSY_COBBLESTONE:
        income: 0.3
        experience: 0.3
      DIAMOND_BLOCK:
        income: 0.3
        experience: 0.3
      GOLD_BLOCK:
        income: 0.3
        experience: 0.3
    Kill:
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Builder:
        income: 10.0
        experience: 10.0
  Digger:
    fullname: Digger
    shortname: D
    description: Копатель. Зарабытывает деньги, добывая землю, гравий и т.д.
    ChatColour: GOLD
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Break:
      DIRT:
        income: 0.1
        experience: 0.1
      GRASS:
        income: 0.1
        experience: 0.1
      GRAVEL:
        income: 0.1
        experience: 0.1
      SAND:
        income: 0.1
        experience: 0.1
      CLAY:
        income: 0.1
        experience: 0.1
    Kill:
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Digger:
        income: 10.0
        experience: 10.0
  Farmer:
    fullname: Farmer
    shortname: Fa
    description: Фермер. Зарабатывает деньги, занимаясь сельским хозяйством.
    ChatColour: BLUE
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Break:
      CROPS-7:
        income: 0.3
        experience: 0.3
      SUGAR_CANE_BLOCK:
        income: 0.3
        experience: 0.3
    Place:
      CROPS-0:
        income: 0.3
        experience: 0.3
      SUGAR_CANE_BLOCK:
        income: 0.2
        experience: 0.2
    Kill:
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Farmer:
        income: 10.0
        experience: 10.0
  Hunter:
    fullname: Hunter
    shortname: H
    description: Охотник. Зарабатывает деньги, убивая животных и монстров.
    ChatColour: RED
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Kill:
      Chicken:
        income: 0.15
        experience: 0.15
      Cow:
        income: 0.15
        experience: 0.15
      Pig:
        income: 0.15
        experience: 0.15
      Sheep:
        income: 0.15
        experience: 0.15
      Wolf:
        income: 0.15
        experience: 0.15
      Creeper:
        income: 0.15
        experience: 0.15
      Skeleton:
        income: 0.15
        experience: 0.15
      Spider:
        income: 0.15
        experience: 0.15
      Zombie:
        income: 0.15
        experience: 0.15
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Woodcutter:
        income: 10.0
        experience: 10.0
      Miner:
        income: 10.0
        experience: 10.0
      Digger:
        income: 10.0
        experience: 10.0
      Farmer:
        income: 10.0
        experience: 10.0
      Builder:
        income: 10.0
        experience: 10.0
      Hunter:
        income: 20.0
        experience: 20.0
  Fisherman:
    fullname: Fisherman
    shortname: Fi
    description: Рыбак. Зарабатывает деньги, занимаясь рыболовством.
    ChatColour: AQUA
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Fish:
      RAW_FISH:
        income: 0.3
        experience: 0.3
    Kill:
      Player:
        income: 7.5
        experience: 7.5
    custom-kill:
      Fisherman:
        income: 10.0
        experience: 10.0
  Weaponsmith:
    fullname: Weaponsmith
    shortname: W
    description: Оружейник. Зарабатывает деньги созданием и починкой оружия.
    ChatColour: DARK_PURPLE
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Craft:
      WOOD_SWORD:
        income: 0.4
        experience: 0.4
      IRON_SWORD:
        income: 0.5
        experience: 0.5
      GOLD_SWORD:
        income: 0.7
        experience: 0.7
      DIAMOND_SWORD:
        income: 0.9
        experience: 0.9
    Repair:
      WOOD_SWORD:
        income: 0.3
        experience: 0.3
      IRON_SWORD:
        income: 0.5
        experience: 0.5
      GOLD_SWORD:
        income: 0.6
        experience: 0.6
      DIAMOND_SWORD:
        income: 0.7
        experience: 0.7
    Smelt:
      IRON_INGOT:
        income: 2.0
        experience: 2.0
      GOLD_INGOT:
        income: 2.0
        experience: 2.0
  Brewer:
    fullname: Brewer
    shortname: Br
    description: Варит зелья. Этим и зарабатывает.
    ChatColour: LIGHT_PURPLE
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Brew:
      NETHER_STALK:
        income: 0.4
        experience: 0.4
      REDSTONE:
        income: 0.6
        experience: 0.6
      GLOWSTONE_DUST:
        income: 0.6
        experience: 0.6
      SPIDER_EYE:
        income: 0.6
        experience: 0.6
      FERMENTED_SPIDER_EYE:
        income: 0.6
        experience: 0.6
      BLAZE_POWDER:
        income: 0.6
        experience: 0.6
      SUGAR:
        income: 0.6
        experience: 0.6
      SPECKLED_MELON:
        income: 1.0
        experience: 1.0
      MAGMA_CREAM:
        income: 1.0
        experience: 1.0
      GHAST_TEAR:
        income: 1.0
        experience: 1.0
  Enchanter:
    fullname: Enchanter
    shortname: E
    description: Зачаровывает оружие. Этим и зарабатывает.
    ChatColour: DARK_BLUE
    chat-display: full
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Enchant:
      WOOD_SWORD:
        income: 2.0
        experience: 2.0
      IRON_SWORD:
        income: 3.0
        experience: 3.0
      GOLD_SWORD:
        income: 4.0
        experience: 4.0
      DIAMOND_SWORD:
        income: 5.0
        experience: 5.0
  None:
    fullname: None
    shortname: N
    ChatColour: WHITE
    chat-display: none
    leveling-progression-equation: 100*((1.13+(0.01*(numjobs-1)))^(joblevel-1))
    income-progression-equation: baseincome*((1.05)^(joblevel-1))
    experience-progression-equation: baseexperience*((1.05)^(joblevel-1))
    Kill:
      Player:
        income: 7.5
